### ISSUE TITLE
Change URLs in example for photos in assets

### ISSUE THREAD

**Issue by Maluzzz** [Maluzzz/random-gallery-svg#2]
Now we have the photos passed to the component in external URLs pass in the **example/src/index.js**
Add the photos to the **example/src/assets** folder to have in local.

**Comment by ameyanrd** [comment]
Hi, I would like to work on the issue.

**Comment by Maluzzz** [comment]
> Hi, I would like to work on the issue.

Thanks I assigned to you 👍

**Comment by melissahuertadev** [comment]
Can I help with this?

**Comment by Maluzzz** [comment]
> Can I help with this?
@ameyanrd Already did it. But I'm going to publish more easy issues very soon (in like 2hours aprox.)

**Comment by Maluzzz** [comment]
Thanks :)
